# Generated by Django 3.2 on 2023-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, verbose_name='Role name')),
                ('can_read', models.BooleanField(default=False, verbose_name='User with this role can read')),
                ('can_post_content', models.BooleanField(default=False, verbose_name='User with this role can post content')),
                ('can_edit_self_content', models.BooleanField(default=False, verbose_name='User with this role can edit self content')),
                ('can_edit_all_content', models.BooleanField(default=False, verbose_name='User with this role can edit all content')),
            ],
        ),
    ]
