# Generated by Django 3.2 on 2023-03-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', max_length=500, verbose_name='biography'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('anon', 'Anonymous'), ('user', 'Authenticated user'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='user', max_length=16, verbose_name='user role'),
        ),
    ]
